# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: app
#   namespace: dev
#   labels:
#     app: app
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: app
#   template:
#     metadata:
#       labels:
#         app: app
#     spec:
#       containers:
#       - name: app
#         image: wil42/playground:v1
#         ports:
#         - containerPort: 8888

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: svc-lsaidi-app
#   labels:
#     run: app
# spec:
#   ports:
#   - port: 8888
#     protocol: TCP
#   selector:
#     run: app

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
        
        
---


apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  ports:
  - port: 8888
    protocol: TCP
  selector:
    run: my-nginx
